- name: LLMNR, NBT-NS and/or mDNS poisoning
  hosts: "{{ host_name | default('srv02', true) }}" # extra-vars
  vars:
    action: "{{ action }}" # extra-vars
  vars_files:
    - ../../vars/breakingbad.json

  roles:
    - role: ../../roles/vulnerabilities/06/enable
      when: action == "enable"
      protocol: "{{ protocol_name | default('all', true) }}" # extra-vars

    - role: ../../roles/vulnerabilities/06/disable
      when: action == "disable"
      protocol: "{{ protocol_name | default('all', true) }}" # extra-vars

    - role: ../../roles/vulnerabilities/06/trigger
      when: action == "trigger"
      user: "{{ user_name | default('walter.white', true) }}" # extra-vars
      share: "{{ share_name | default('fakeshare', true) }}" # extra-vars (max 15 chars for NBT-NS)
  gather_facts: false